import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";
import { getConfigurationService } from "../../configuration/configuration.service.js";
import { getConvertProjectModelWorker } from "./convertProjectModel.worker.js";
import { getConvertTerrainWorker } from "./convertTerrain.worker.js";
import { getConvert3DTilesWorker } from "./convert3DTiles.worker.js";

const updateConverterWorkerConfigurationsWorker = createWorker()
  .queue("{updateConverterWorkerConfigurations-queue}")
  .job<Job<void, void>>()
  .upsertJobScheduler("updateConverterWorkerConfigurationsScheduler", {
    every: 5 * 60 * 1000, // every 5 minutes
  })
  .connection(defaultConnection)
  .processor(async (_, { services, workers }) => {
    if (process.env.DISABLED_WORKERS === "true") return;

    const configurationService = await getConfigurationService(services);

    const convertProjectModelWorker = getConvertProjectModelWorker(workers);
    const convertTerrainWorker = getConvertTerrainWorker(workers);
    const convert3DTilesWorker = getConvert3DTilesWorker(workers);

    const config = await configurationService.getConfiguration();

    convertProjectModelWorker.opts.concurrency =
      config.maxParallelFileConversions;
    convert3DTilesWorker.opts.concurrency =
      config.maxParallelBaseLayerConversions;
    convertTerrainWorker.opts.concurrency =
      config.maxParallelBaseLayerConversions;
  });

/*
AUTOGENERATED!
*/

export { updateConverterWorkerConfigurationsWorker };
export type UpdateConverterWorkerConfigurationsWorker =
  (typeof updateConverterWorkerConfigurationsWorker)["worker"];
export type UpdateConverterWorkerConfigurationsWorkerQueue =
  (typeof updateConverterWorkerConfigurationsWorker)["queue"];
export type UpdateConverterWorkerConfigurationsWorkerJob =
  (typeof updateConverterWorkerConfigurationsWorker)["job"];

export function getUpdateConverterWorkerConfigurationsWorker(
  deps: WorkerContainer
) {
  return deps.get<UpdateConverterWorkerConfigurationsWorker>(
    updateConverterWorkerConfigurationsWorker.queueName
  );
}
export function getUpdateConverterWorkerConfigurationsWorkerQueue(
  deps: QueueContainer
) {
  return deps.get<UpdateConverterWorkerConfigurationsWorkerQueue>(
    updateConverterWorkerConfigurationsWorker.queueName
  );
}
