import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import { getConverter3DService } from "../converter3D.service.js";
import defaultConnection from "../../connection.js";

const convertTerrainWorker = createWorker()
  .queue("convertTerrain-queue")
  .sandboxedJob<
    SandboxedJob<
      {
        blobName: string;
        srcSRS: string;
        containerName: string;
        localProcessorFolder: string;
      },
      void
    >
  >()
  .on("active", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.blobName,
      0,
      "ACTIVE"
    );
  })
  .on("progress", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.blobName,
      +job.progress.valueOf(),
      "ACTIVE"
    );
  })
  .on("completed", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.blobName,
      1,
      "ACTIVE"
    );
  })
  .on("failed", async ({ services }, job) => {
    if (!job) return;

    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.blobName,
      +job.progress.valueOf(),
      "ACTIVE"
    );
  })
  .options({
    concurrency: 1,
    useWorkerThreads: true,
    removeOnComplete: { count: 100, age: 3600 },
    removeOnFail: { count: 200, age: 24 * 3600 },
  })
  .connection(defaultConnection)
  .processor(
    new URL(
      "./convertTerrain.sandboxedWorker.js",
      import.meta.url
    )
  );

/*
AUTOGENERATED!
*/

export { convertTerrainWorker };
export type ConvertTerrainWorker = (typeof convertTerrainWorker)["worker"];
export type ConvertTerrainWorkerQueue = (typeof convertTerrainWorker)["queue"];
export type ConvertTerrainWorkerJob = (typeof convertTerrainWorker)["job"];

export function getConvertTerrainWorker(deps: WorkerContainer) {
  return deps.get<ConvertTerrainWorker>(convertTerrainWorker.queueName);
}
export function getConvertTerrainWorkerQueue(deps: QueueContainer) {
  return deps.get<ConvertTerrainWorkerQueue>(convertTerrainWorker.queueName);
}
