import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import { getConverter3DService } from "../converter3D.service.js";
import defaultConnection from "../../connection.js";

const convert3DTilesWorker = createWorker()
  .queue("{convert3DTiles-queue}")
  .sandboxedJob<
    SandboxedJob<
      {
        blobName: string;
        containerName: string;
        id: string;
        srcSRS: string;
        localProcessorFolder: string;
        threadCount: number;
      },
      void
    >
  >()
  .on("active", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(job.data.id, 0, "ACTIVE");
  })
  .on("progress", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.id,
      +job.progress.valueOf(),
      "ACTIVE"
    );
  })
  .on("completed", async ({ services }, job) => {
    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(job.data.id, 1, "COMPLETED");
  })
  .on("failed", async ({ services }, job) => {
    if (!job) return;

    const converter3DService = await getConverter3DService(services);

    await converter3DService.updateBaseLayerStatus(
      job.data.id,
      +job.progress.valueOf(),
      "FAILED"
    );
  })
  .options({
    concurrency: 1,
    removeOnComplete: { count: 100, age: 24 * 3600 },
    removeOnFail: { count: 200, age: 24 * 3600 },
    stalledInterval: 120_000,
  })
  .connection(defaultConnection)
  .processor(new URL("./convert3DTiles.sandboxedWorker.js", import.meta.url));

/*
AUTOGENERATED!
*/

export { convert3DTilesWorker };
export type Convert3DTilesWorker = (typeof convert3DTilesWorker)["worker"];
export type Convert3DTilesWorkerQueue = (typeof convert3DTilesWorker)["queue"];
export type Convert3DTilesWorkerJob = (typeof convert3DTilesWorker)["job"];

export function getConvert3DTilesWorker(deps: WorkerContainer) {
  return deps.get<Convert3DTilesWorker>(convert3DTilesWorker.queueName);
}
export function getConvert3DTilesWorkerQueue(deps: QueueContainer) {
  return deps.get<Convert3DTilesWorkerQueue>(convert3DTilesWorker.queueName);
}
