import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import { getBlobStorageService } from "../../blobStorage/blobStorage.service.js";
import { getConverter3DService } from "../converter3D.service.js";
import defaultConnection from "../../connection.js";

const convertProjectModelWorker = createWorker()
  .queue("{convertProjectModel-queue}")
  .sandboxedJob<
    SandboxedJob<
      {
        blobName: string;
        fileName: string;
        containerName: string;
        srcSRS: string;
        secret: string;
      },
      {
        modelMatrix: number[];
        collectableBlobName: string;
        containerName: string;
        secret: string;
      }
    >
  >()
  .on("failed", async ({ services }, job) => {
    if (!job) return;

    const converter3DService = await getConverter3DService(services);
  })
  .on("completed", async ({ services }, job) => {
    const blobStorageService = await getBlobStorageService(services);

    await blobStorageService.deleteLater(
      job.data.containerName,
      job.data.blobName,
      2 * 60 * 60 * 1000
    );
  })
  .options({
    concurrency: 2,
    removeOnFail: { count: 200, age: 24 * 3600 },
    stalledInterval: 120_000,
  })
  .connection(defaultConnection)
  .processor(
    new URL("./convertProjectModel.sandboxedWorker.js", import.meta.url)
  );

/*
AUTOGENERATED!
*/

export { convertProjectModelWorker };
export type ConvertProjectModelWorker =
  (typeof convertProjectModelWorker)["worker"];
export type ConvertProjectModelWorkerQueue =
  (typeof convertProjectModelWorker)["queue"];
export type ConvertProjectModelWorkerJob =
  (typeof convertProjectModelWorker)["job"];

export function getConvertProjectModelWorker(deps: WorkerContainer) {
  return deps.get<ConvertProjectModelWorker>(
    convertProjectModelWorker.queueName
  );
}
export function getConvertProjectModelWorkerQueue(deps: QueueContainer) {
  return deps.get<ConvertProjectModelWorkerQueue>(
    convertProjectModelWorker.queueName
  );
}
