import {
  createWorker,
  QueueContainer,
  WorkerContainer,
} from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import { getConverter3DService } from "../converter3D.service.js";
import defaultConnection from "../../connection.js";

const convertTerrainWorker = createWorker()
  .queue("{convertTerrain-queue}")
  .sandboxedJob<
    SandboxedJob<
      {
        blobName: string;
        srcSRS: string;
        id: string;
        containerName: string;
        localProcessorFolder: string;
        threadCount: number;
      },
      void
    >
  >()
  .on("active", async ({ services }, job) => {
    try {
      const converter3DService = await getConverter3DService(services);

      await converter3DService.updateBaseLayerStatus(job.data.id, 0, "ACTIVE");
    } catch (e) {
      console.error(e);
    }
  })
  .on("progress", async ({ services }, job) => {
    try {
      const converter3DService = await getConverter3DService(services);

      await converter3DService.updateBaseLayerStatus(
        job.data.id,
        +job.progress.valueOf(),
        "ACTIVE"
      );
    } catch (e) {
      console.error(e);
    }
  })
  .on("completed", async ({ services }, job) => {
    try {
      const converter3DService = await getConverter3DService(services);

      await converter3DService.updateBaseLayerStatus(
        job.data.id,
        1,
        "COMPLETED"
      );
    } catch (e) {
      console.error(e);
    }
  })
  .on("failed", async ({ services }, job) => {
    try {
      if (!job) return;

      const converter3DService = await getConverter3DService(services);

      await converter3DService.updateBaseLayerStatus(
        job.data.id,
        +job.progress.valueOf(),
        "FAILED"
      );
    } catch (e) {
      console.error(e);
    }
  })
  .options({
    concurrency: 1,
    removeOnComplete: { count: 100, age: 3600 },
    removeOnFail: { count: 200, age: 24 * 3600 },
    stalledInterval: 120_000,
  })
  .connection(defaultConnection)
  .processor(new URL("./convertTerrain.sandboxedWorker.js", import.meta.url));

/*
AUTOGENERATED!
*/

export { convertTerrainWorker };
export type ConvertTerrainWorker = (typeof convertTerrainWorker)["worker"];
export type ConvertTerrainWorkerQueue = (typeof convertTerrainWorker)["queue"];
export type ConvertTerrainWorkerJob = (typeof convertTerrainWorker)["job"];

export function getConvertTerrainWorker(deps: WorkerContainer) {
  return deps.get<ConvertTerrainWorker>(convertTerrainWorker.queueName);
}
export function getConvertTerrainWorkerQueue(deps: QueueContainer) {
  return deps.get<ConvertTerrainWorkerQueue>(convertTerrainWorker.queueName);
}
