import {
  createWorker,
} from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";
import { BullMQOtel } from "bullmq-otel";
import { getConverter3DConvertTerrainWorker, getConverter3DConvertProjectModelWorker, getConverter3DConvert3DTilesWorker, getConfigurationService } from "../../@internals/index.js"

const updateConverterWorkerConfigurationsWorker = createWorker()
  .queue("{converter3D-updateConverterWorkerConfigurations-queue}")
  .job<Job<void, void>>()
  .upsertJobScheduler("updateConverterWorkerConfigurationsScheduler", {
    every: 60 * 60 * 1000, // every 5 minutes
  })
  .options({ telemetry: new BullMQOtel("bullmq") })
  .connection(defaultConnection)
  .processor(async (_, { services, workers }) => {
    if (process.env.DISABLED_WORKERS === "true") return;

    const configurationService = await getConfigurationService(services);

    const convertProjectModelWorker = getConverter3DConvertProjectModelWorker(workers);
    const convertTerrainWorker = getConverter3DConvertTerrainWorker(workers);
    const convert3DTilesWorker = getConverter3DConvert3DTilesWorker(workers);

    const config = await configurationService.getConfiguration();

    convertProjectModelWorker.opts.concurrency =
      config.maxParallelFileConversions;
    convert3DTilesWorker.opts.concurrency =
      config.maxParallelBaseLayerConversions;
    convertTerrainWorker.opts.concurrency =
      config.maxParallelBaseLayerConversions;
  });

/*
AUTOGENERATED!
*/

export default updateConverterWorkerConfigurationsWorker;