/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

import appDownloadService from "../appDownload/appDownload.service.js";
import authService from "../auth/auth.service.js";
import baseLayerService from "../baseLayer/baseLayer.service.js";
import blobStorageService from "../blobStorage/blobStorage.service.js";
import cacheService from "../cache/cache.service.js";
import configurationService from "../configuration/configuration.service.js";
import converter3DService from "../converter3D/converter3D.service.js";
import dbService from "../db/db.service.js";
import emailService from "../email/email.service.js";
import eventsService from "../events/events.service.js";
import notificationService from "../notification/notification.service.js";
import prismaService from "../prisma/prisma.service.js";
import projectService from "../project/project.service.js";
import statsService from "../stats/stats.service.js";
import tokenService from "../token/token.service.js";
import translationService from "../translation/translation.service.js";
import userService from "../user/user.service.js";
import blobStorageDeleteBlobWorker from "../blobStorage/workers/deleteBlob.worker.js";
import converter3DConvert3DTilesWorker from "../converter3D/workers/convert3DTiles.worker.js";
import converter3DConvertProjectModelWorker from "../converter3D/workers/convertProjectModel.worker.js";
import converter3DConvertTerrainWorker from "../converter3D/workers/convertTerrain.worker.js";
import converter3DConvertWMSWMTSWorker from "../converter3D/workers/convertWMSWMTS.worker.js";
import converter3DUpdateConverterWorkerConfigurationsWorker from "../converter3D/workers/updateConverterWorkerConfigurations.worker.js";
import eventsRemoveOldEventsWorker from "../events/workers/removeOldEvents.worker.js";
import userDeleteInactiveUsersWorker from "../user/workers/deleteInactiveUsers.worker.js";

export type AppDownloadService = InferService<typeof appDownloadService>;
export type AuthService = InferService<typeof authService>;
export type BaseLayerService = InferService<typeof baseLayerService>;
export type BlobStorageService = InferService<typeof blobStorageService>;
export type CacheService = InferService<typeof cacheService>;
export type ConfigurationService = InferService<typeof configurationService>;
export type Converter3DService = InferService<typeof converter3DService>;
export type DbService = InferService<typeof dbService>;
export type EmailService = InferService<typeof emailService>;
export type EventsService = InferService<typeof eventsService>;
export type NotificationService = InferService<typeof notificationService>;
export type PrismaService = InferService<typeof prismaService>;
export type ProjectService = InferService<typeof projectService>;
export type StatsService = InferService<typeof statsService>;
export type TokenService = InferService<typeof tokenService>;
export type TranslationService = InferService<typeof translationService>;
export type UserService = InferService<typeof userService>;
export type BlobStorageDeleteBlobWorker = (typeof blobStorageDeleteBlobWorker)["worker"];
export type BlobStorageDeleteBlobWorkerQueue = (typeof blobStorageDeleteBlobWorker)["queue"];
export type BlobStorageDeleteBlobWorkerJob = (typeof blobStorageDeleteBlobWorker)["job"];
export type Converter3DConvert3DTilesWorker = (typeof converter3DConvert3DTilesWorker)["worker"];
export type Converter3DConvert3DTilesWorkerQueue = (typeof converter3DConvert3DTilesWorker)["queue"];
export type Converter3DConvert3DTilesWorkerJob = (typeof converter3DConvert3DTilesWorker)["job"];
export type Converter3DConvertProjectModelWorker = (typeof converter3DConvertProjectModelWorker)["worker"];
export type Converter3DConvertProjectModelWorkerQueue = (typeof converter3DConvertProjectModelWorker)["queue"];
export type Converter3DConvertProjectModelWorkerJob = (typeof converter3DConvertProjectModelWorker)["job"];
export type Converter3DConvertTerrainWorker = (typeof converter3DConvertTerrainWorker)["worker"];
export type Converter3DConvertTerrainWorkerQueue = (typeof converter3DConvertTerrainWorker)["queue"];
export type Converter3DConvertTerrainWorkerJob = (typeof converter3DConvertTerrainWorker)["job"];
export type Converter3DConvertWMSWMTSWorker = (typeof converter3DConvertWMSWMTSWorker)["worker"];
export type Converter3DConvertWMSWMTSWorkerQueue = (typeof converter3DConvertWMSWMTSWorker)["queue"];
export type Converter3DConvertWMSWMTSWorkerJob = (typeof converter3DConvertWMSWMTSWorker)["job"];
export type Converter3DUpdateConverterWorkerConfigurationsWorker = (typeof converter3DUpdateConverterWorkerConfigurationsWorker)["worker"];
export type Converter3DUpdateConverterWorkerConfigurationsWorkerQueue = (typeof converter3DUpdateConverterWorkerConfigurationsWorker)["queue"];
export type Converter3DUpdateConverterWorkerConfigurationsWorkerJob = (typeof converter3DUpdateConverterWorkerConfigurationsWorker)["job"];
export type EventsRemoveOldEventsWorker = (typeof eventsRemoveOldEventsWorker)["worker"];
export type EventsRemoveOldEventsWorkerQueue = (typeof eventsRemoveOldEventsWorker)["queue"];
export type EventsRemoveOldEventsWorkerJob = (typeof eventsRemoveOldEventsWorker)["job"];
export type UserDeleteInactiveUsersWorker = (typeof userDeleteInactiveUsersWorker)["worker"];
export type UserDeleteInactiveUsersWorkerQueue = (typeof userDeleteInactiveUsersWorker)["queue"];
export type UserDeleteInactiveUsersWorkerJob = (typeof userDeleteInactiveUsersWorker)["job"];

export function getAppDownloadService(deps: ServiceContainer) {
    return deps.get<AppDownloadService>(appDownloadService.name);
}
export function getAuthService(deps: ServiceContainer) {
    return deps.get<AuthService>(authService.name);
}
export function getBaseLayerService(deps: ServiceContainer) {
    return deps.get<BaseLayerService>(baseLayerService.name);
}
export function getBlobStorageService(deps: ServiceContainer) {
    return deps.get<BlobStorageService>(blobStorageService.name);
}
export function getCacheService(deps: ServiceContainer) {
    return deps.get<CacheService>(cacheService.name);
}
export function getConfigurationService(deps: ServiceContainer) {
    return deps.get<ConfigurationService>(configurationService.name);
}
export function getConverter3DService(deps: ServiceContainer) {
    return deps.get<Converter3DService>(converter3DService.name);
}
export function getDbService(deps: ServiceContainer) {
    return deps.get<DbService>(dbService.name);
}
export function getEmailService(deps: ServiceContainer) {
    return deps.get<EmailService>(emailService.name);
}
export function getEventsService(deps: ServiceContainer) {
    return deps.get<EventsService>(eventsService.name);
}
export function getNotificationService(deps: ServiceContainer) {
    return deps.get<NotificationService>(notificationService.name);
}
export function getPrismaService(deps: ServiceContainer) {
    return deps.get<PrismaService>(prismaService.name);
}
export function getProjectService(deps: ServiceContainer) {
    return deps.get<ProjectService>(projectService.name);
}
export function getStatsService(deps: ServiceContainer) {
    return deps.get<StatsService>(statsService.name);
}
export function getTokenService(deps: ServiceContainer) {
    return deps.get<TokenService>(tokenService.name);
}
export function getTranslationService(deps: ServiceContainer) {
    return deps.get<TranslationService>(translationService.name);
}
export function getUserService(deps: ServiceContainer) {
    return deps.get<UserService>(userService.name);
}
export function getBlobStorageDeleteBlobWorker(deps: WorkerContainer) {
  return deps.get<BlobStorageDeleteBlobWorker>(blobStorageDeleteBlobWorker.queueName);
}
export function getBlobStorageDeleteBlobWorkerQueue(deps: QueueContainer) {
  return deps.get<BlobStorageDeleteBlobWorkerQueue>(blobStorageDeleteBlobWorker.queueName);
}
export function getConverter3DConvert3DTilesWorker(deps: WorkerContainer) {
  return deps.get<Converter3DConvert3DTilesWorker>(converter3DConvert3DTilesWorker.queueName);
}
export function getConverter3DConvert3DTilesWorkerQueue(deps: QueueContainer) {
  return deps.get<Converter3DConvert3DTilesWorkerQueue>(converter3DConvert3DTilesWorker.queueName);
}
export function getConverter3DConvertProjectModelWorker(deps: WorkerContainer) {
  return deps.get<Converter3DConvertProjectModelWorker>(converter3DConvertProjectModelWorker.queueName);
}
export function getConverter3DConvertProjectModelWorkerQueue(deps: QueueContainer) {
  return deps.get<Converter3DConvertProjectModelWorkerQueue>(converter3DConvertProjectModelWorker.queueName);
}
export function getConverter3DConvertTerrainWorker(deps: WorkerContainer) {
  return deps.get<Converter3DConvertTerrainWorker>(converter3DConvertTerrainWorker.queueName);
}
export function getConverter3DConvertTerrainWorkerQueue(deps: QueueContainer) {
  return deps.get<Converter3DConvertTerrainWorkerQueue>(converter3DConvertTerrainWorker.queueName);
}
export function getConverter3DConvertWMSWMTSWorker(deps: WorkerContainer) {
  return deps.get<Converter3DConvertWMSWMTSWorker>(converter3DConvertWMSWMTSWorker.queueName);
}
export function getConverter3DConvertWMSWMTSWorkerQueue(deps: QueueContainer) {
  return deps.get<Converter3DConvertWMSWMTSWorkerQueue>(converter3DConvertWMSWMTSWorker.queueName);
}
export function getConverter3DUpdateConverterWorkerConfigurationsWorker(deps: WorkerContainer) {
  return deps.get<Converter3DUpdateConverterWorkerConfigurationsWorker>(converter3DUpdateConverterWorkerConfigurationsWorker.queueName);
}
export function getConverter3DUpdateConverterWorkerConfigurationsWorkerQueue(deps: QueueContainer) {
  return deps.get<Converter3DUpdateConverterWorkerConfigurationsWorkerQueue>(converter3DUpdateConverterWorkerConfigurationsWorker.queueName);
}
export function getEventsRemoveOldEventsWorker(deps: WorkerContainer) {
  return deps.get<EventsRemoveOldEventsWorker>(eventsRemoveOldEventsWorker.queueName);
}
export function getEventsRemoveOldEventsWorkerQueue(deps: QueueContainer) {
  return deps.get<EventsRemoveOldEventsWorkerQueue>(eventsRemoveOldEventsWorker.queueName);
}
export function getUserDeleteInactiveUsersWorker(deps: WorkerContainer) {
  return deps.get<UserDeleteInactiveUsersWorker>(userDeleteInactiveUsersWorker.queueName);
}
export function getUserDeleteInactiveUsersWorkerQueue(deps: QueueContainer) {
  return deps.get<UserDeleteInactiveUsersWorkerQueue>(userDeleteInactiveUsersWorker.queueName);
}

