import { createWorker } from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import defaultConnection from "../../connection.js";

const helloWorldWorker = createWorker()
    .queue("{test-helloWorld-queue}")
    .sandboxedJob<SandboxedJob<{}, void>>()
    .upsertJobScheduler("test", {
        every: 5000,
    })
    .connection(defaultConnection)
    .processor(new URL("./test/workers/helloWorld.sandboxedWorker.js", import.meta.url));

/*
AUTOGENERATED!
*/

export default helloWorldWorker;
