import { createService } from "@csi-foxbyte/fastify-toab";
import {
  getConfigurationService,
  getNotificationService,
  getPrismaService,
  getProjectService,
  getTranslationService,
} from "../@internals/index.js";
import dayjs from "dayjs";

const userService = createService(
  "user",
  async ({ services }) => {
    const prismaService = await getPrismaService(services);
    const projectService = await getProjectService(services);
    const notificationService = await getNotificationService(services);
    const translationService = await getTranslationService(services);
    const configService = await getConfigurationService(services);

    async function remove(id: string) {
      const projects = await prismaService.project.findMany({
        where: { ownerId: id },
        select: { id: true },
      });

      for (const project of projects) {
        await projectService.deleteProject(project.id);
      }

      await prismaService.user.delete({ where: { id } });
    }

    return {
      remove,
      async informInactiveUsersPreRemoval() {
        const users = await prismaService.user.findMany({
          where: {
            sessions: {
              every: {
                updatedAt: {
                  lt: dayjs().add(365, "day").subtract(30, "day").toISOString(),
                },
              },
            },
          },
        });

        const config = await configService.getConfiguration();

        const translators = {
          DE: translationService.getTranslator("de"),
          EN: translationService.getTranslator("en"),
        };

        const templates = {
          DE: Handlebars.compile(config.predeletionEmailDE),
          EN: Handlebars.compile(config.predeletionEmailEN),
        };

        await notificationService.notify(
          users.map((user) => ({
            attachments: [],
            content: templates[user.language ?? "EN"]({
              user: {
                name: user.name,
                email: user.email,
              },
            }),
            from: null,
            to: user.email,
            title: translators[user.language ?? "EN"](
              "notifications.predeletion-due-to-inactivity-title"
            ),
          }))
        );
      },
      async removeInactiveUsers() {
        const users = await prismaService.user.findMany({
          where: {
            sessions: {
              every: {
                updatedAt: {
                  lt: dayjs().add(365, "day").toISOString(),
                },
              },
            },
          },
        });

        for (const user of users) {
          await remove(user.id);
        }
      },
      async info(id: string) {
        const user = await prismaService.user.findFirstOrThrow({
          where: { id },
          select: {
            name: true,
            email: true,
          },
        });

        return {
          ...user,
          name: user.name ?? "-",
        };
      },
    };
  },
  {
    scope: "REQUEST",
  }
);

/*
AUTOGENERATED!
*/

export default userService;
