import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { getDbService } from "../db/db.service.js";
import { getCacheService } from "../cache/cache.service.js";

const configurationService = createService(
  "configuration",
  async ({ services }) => {
    const dbService = await getDbService(services);

    const cacheService = await getCacheService(services);

    return {
      async getConfiguration() {
        return await cacheService.wrap(
          "__config__",
          async () => {
            const config =
              await dbService.rawClient.configuration.findFirstOrThrow({
                select: {
                  defaultEPSG: true,
                  globalStartPointX: true,
                  globalStartPointY: true,
                  globalStartPointZ: true,
                  invitationEmailText: true,
                  localProcessorFolder: true,
                  maxParallelBaseLayerConversions: true,
                  maxParallelFileConversions: true,
                },
              });

            return config;
          },
          60_000
        ); // hold in cache for 1 minute
      },
    };
  },
  {
    buildTime: "INSTANT",
  }
);

/*
AUTOGENERATED!
*/

export { configurationService };
export type ConfigurationService = InferService<typeof configurationService>;
export function getConfigurationService(deps: ServiceContainer) {
  return deps.get<ConfigurationService>(configurationService.name);
}
