import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { PrismaClient } from "@prisma/client";
import realtimeExtension from "./extensions/realtimeExtension.js";

const prismaService = createService("prisma", async () => {
  const prisma = new PrismaClient().$extends(
    realtimeExtension({ intervalMs: 5_000 })
  );

  return prisma;
});

/*
AUTOGENERATED!
*/

export { prismaService };
export type PrismaService = InferService<typeof prismaService>;
export function getPrismaService(deps: ServiceContainer) {
  return deps.get<PrismaService>(prismaService.name);
}
