import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { enhance } from "@zenstackhq/runtime";
import { getAuthService } from "../auth/auth.service.js";
import { getPrismaService } from "../prisma/prisma.service.js";

const dbService = createService("db", async ({ services }) => {
  const prismaService = await getPrismaService(services);

  const authService = await getAuthService(services);

  const session = await authService.getSession();

  if (!session) throw new Error("Unauthenticated!");

  return enhance(prismaService, session);
});

/*
AUTOGENERATED!
*/

export { dbService };
export type DbService = InferService<typeof dbService>;
export function getDbService(deps: ServiceContainer) {
  return deps.get<DbService>(dbService.name);
}
