import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { PrismaClient } from "@prisma/client";
import { enhance } from "@zenstackhq/runtime";
import { getAuthService } from "../auth/auth.service.js";
import realtimeExtension from "./extensions/realtimeExtension.js";

const dbService = createService("db", async ({ services }) => {
  const prisma = new PrismaClient().$extends(
    realtimeExtension({ intervalMs: 5_000 })
  );

  return {
    rawClient: prisma,
    /**
     * Needs to be called within a request context!
     * @returns
     */
    async getEnhancedClient() {
      const authService = await getAuthService(services);

      const session = await authService.getSession();

      if (!session) throw new Error("Unauthenticated!");

      return enhance(prisma, session);
    },
  };
});

/*
AUTOGENERATED!
*/

export { dbService };
export type DbService = InferService<typeof dbService>;
export function getDbService(deps: ServiceContainer) {
  return deps.get<DbService>(dbService.name);
}
