import {
  createService,
} from "@csi-foxbyte/fastify-toab";
import { enhance } from "@zenstackhq/runtime";
import { getAuthService, getPrismaService } from "../@internals/index.js";
import realtimeExtension from "../prisma/extensions/realtimeExtension.js";

const dbService = createService("db", async ({ services }) => {
  const prismaService = await getPrismaService(services);

  const authService = await getAuthService(services);

  const session = await authService.getSession();

  if (!session) throw new Error("Unauthenticated!");

  return enhance(prismaService, session).$extends(realtimeExtension());
}, {
  scope: "REQUEST",
});

/*
AUTOGENERATED!
*/

export default dbService;