import { createController, GenericRouteError } from "@csi-foxbyte/fastify-toab";
import { authMiddleware } from "../auth/auth.middleware.js";
import { Type } from "@sinclair/typebox";
import { getProjectService } from "./project.service.js";
import { projectDTO } from "./project.dto.js";

const projectController = createController()
  .use(authMiddleware)
  .rootPath("/project");

projectController
  .addRoute("GET", "/:id")
  .params(Type.Object({ id: Type.String() }))
  .output(projectDTO)
  .handler(async ({ params, services }) => {
    const projectService = await getProjectService(services);

    try {
      return await projectService.getProject(params.id);
    } catch (e) {
      console.error(e);
      throw new GenericRouteError("BAD_REQUEST", "Project not found.");
    }
  });

projectController
  .addRoute("POST", "/:id")
  .body(projectDTO)
  .handler(async ({ body, services }) => {
    const projectService = await getProjectService(services);

    return await projectService.saveProject(body);
  });

/*
AUTOGENERATED!
*/

export { projectController };
