import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import { JWTPayload, jwtVerify, SignJWT } from "jose";

const tokenService = createService("token", async () => {
  const secret = new TextEncoder().encode(process.env.AUTH_SECRET!);

  return {
    async createToken<T extends JWTPayload>(
      payload: T,
      expirationTime: number | string | Date
    ) {
      return new SignJWT(payload)
        .setAudience("urn:fhhvr")
        .setIssuer("urn:fhhvr")
        .setExpirationTime(expirationTime)
        .setIssuedAt()
        .setNotBefore(new Date())
        .setProtectedHeader({
          alg: "HS256",
        })
        .sign(secret);
    },
    async verifyToken<T extends JWTPayload>(token: string) {
      return jwtVerify<T>(token, secret, {
        audience: "urn:fhhvr",
        issuer: "urn:fhhvr",
        algorithms: ["HS256"],
        clockTolerance: "5 minutes",
      });
    },
  };
});

/*
AUTOGENERATED!
*/

export { tokenService };
export type TokenService = InferService<typeof tokenService>;
export function getTokenService(deps: ServiceContainer) {
  return deps.get<TokenService>(tokenService.name);
}
