import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";
import dayjs from "dayjs";
import { getAuthService } from "../auth/auth.service.js";
import { getDbService } from "../db/db.service.js";
import { getPrismaService } from "../prisma/prisma.service.js";

const eventsService = createService("events", async ({ services }) => {
  const HEARTBEAT_DELAY_MS = 15_000;
  const HEARTBEAT_CHECK_MS = 20_000;

  const dbService = await getDbService(services);
  const prismaService = await getPrismaService(services);
  const authService = await getAuthService(services);

  async function fetchAll() {
    return await dbService.event.findMany({
      select: {
        title: true,
        status: true,
        joinCode: true,
      },
    });
  }

  async function fetchStatus(id: string) {
    return await dbService.event.findFirstOrThrow({
      where: {
        id,
      },
      select: {
        joinCode: true,
        status: true,
      },
    });
  }

  async function checkHeartbeat(id: string) {
    const { heartbeatTimestamp, status } =
      await dbService.event.findFirstOrThrow({
        where: { id },
        select: { heartbeatTimestamp: true, status: true },
      });

    if (status !== "ACTIVE") return;

    if (
      dayjs(heartbeatTimestamp).isBefore(
        dayjs().subtract(HEARTBEAT_DELAY_MS, "second")
      )
    )
      return;

    await dbService.event.update({
      where: {
        id,
      },
      data: {
        status: "MISSING_HOST",
      },
    });
  }

  return {
    async createEvent({
      attendees,
      endTime,
      startTime,
      status,
      title,
    }: {
      endTime: string;
      startTime: string;
      status: string;
      title: string;
      attendees: string[];
    }) {
      await dbService.event.create({
        data: {
          endTime,
          startTime,
          status,
          title,
          owner: {
            connect: {
              email: (await authService.getSession())!.user.email,
            },
          },
          attendees: {
            createMany: {
              data: attendees.map((attendee) => ({ userId: attendee })),
            },
          },
        },
      });
    },

    async updateEvent({
      id,
      attendees,
      endTime,
      startTime,
      status,
      title,
    }: {
      id: string;
      endTime?: string;
      startTime?: string;
      status?: string;
      title?: string;
      attendees?: string[];
    }) {
      return await dbService.event.update({
        data: {
          endTime,
          startTime,
          status,
          title,
          attendees: attendees
            ? {
                deleteMany: {},
                createMany: {
                  data: attendees.map((attendee) => ({ userId: attendee })),
                },
              }
            : undefined,
        },
        where: {
          id,
        },
      });
    },

    fetchAll,

    fetchStatus,

    list() {
      return prismaService.event.subscribe({ operations: ["*"] });
    },

    status(id: string) {
      return prismaService.event.subscribe({ operations: ["*"] });
    },

    async setHeartbeat(id: string) {
      await dbService.event.update({
        where: {
          id,
        },
        data: {
          heartbeatTimestamp: new Date().toISOString(),
        },
      });

      setTimeout(() => checkHeartbeat(id), HEARTBEAT_CHECK_MS);
    },

    checkHeartbeat,

    async hostSession(id: string, joinCode: string) {
      await dbService.event.update({
        where: {
          id,
        },
        data: {
          status: "ACTIVE",
          heartbeatTimestamp: new Date().toISOString(),
          joinCode,
        },
      });

      setTimeout(() => checkHeartbeat(id), HEARTBEAT_CHECK_MS);
    },

    async endSession(id: string) {
      await dbService.event.update({
        where: {
          id,
        },
        data: {
          status: "END",
          joinCode: null,
          heartbeatTimestamp: null,
        },
      });
    },

    async rehostSession(id: string, joinCode: string) {
      await dbService.event.update({
        where: {
          id,
        },
        data: {
          status: "ACTIVE",
          joinCode,
          heartbeatTimestamp: new Date().toISOString(),
        },
      });
    },
  };
});

/*
AUTOGENERATED!
*/

export { eventsService };
export type EventsService = InferService<typeof eventsService>;
export function getEventsService(deps: ServiceContainer) {
  return deps.get<EventsService>(eventsService.name);
}
