import { createController } from "@csi-foxbyte/fastify-toab";
import { Type } from "@sinclair/typebox";
import { on } from "events";
import { authMiddleware } from "../auth/auth.middleware.js";
import {
  eventsCreateRequestDTO,
  eventsHostRequestDTO,
  eventsUpdateRequestDTO,
} from "./events.dto.js";
import { getEventsService } from "./events.service.js";

const eventsController = createController()
  .use(authMiddleware)
  .rootPath("/events");

eventsController
  .addRoute("SSE", "/")
  .handler(async function* ({ services, signal }) {
    const eventsService = await getEventsService(services);

    const events = eventsService.list();

    for await (const value of on(events, "change", { signal })) {
      yield value;
    }
  });

eventsController
  .addRoute("POST", "/create")
  .body(eventsCreateRequestDTO)
  .handler(async ({ services, body }) => {
    const eventsService = await getEventsService(services);

    await eventsService.createEvent(body);
  });

eventsController
  .addRoute("POST", "/update")
  .body(eventsUpdateRequestDTO)
  .handler(async ({ services, body }) => {
    const eventsService = await getEventsService(services);

    await eventsService.updateEvent(body);
  });

eventsController
  .addRoute("SSE", "/:id/status")
  .params(Type.Object({ id: Type.String() }))
  .handler(async function* ({ services, signal, params }) {
    const eventsService = await getEventsService(services);

    const events = eventsService.status(params.id);

    for await (const value of on(events, "change", { signal })) {
      yield value;
    }
  });

eventsController
  .addRoute("POST", "/:id/heartbeat")
  .params(Type.Object({ id: Type.String() }))
  .handler(async ({ services, params }) => {
    const eventsService = await getEventsService(services);

    await eventsService.setHeartbeat(params.id);
  });

eventsController
  .addRoute("POST", "/:id/host")
  .body(eventsHostRequestDTO)
  .params(Type.Object({ id: Type.String() }))
  .handler(async ({ services, params, body }) => {
    const eventsService = await getEventsService(services);

    await eventsService.hostSession(params.id, body.joinCode);
  });

eventsController
  .addRoute("POST", "/:id/end")
  .params(Type.Object({ id: Type.String() }))
  .handler(async ({ services, params }) => {
    const eventsService = await getEventsService(services);

    await eventsService.endSession(params.id);
  });

eventsController
  .addRoute("POST", "/:id/rehost")
  .body(eventsHostRequestDTO)
  .params(Type.Object({ id: Type.String() }))
  .handler(async ({ services, params, body }) => {
    const eventsService = await getEventsService(services);

    await eventsService.rehostSession(params.id, body);
  });

/*
AUTOGENERATED!
*/

export { eventsController };
