import { createController } from "@csi-foxbyte/fastify-toab";
import {
  downloadProjectModelRequestDTIO,
  getProjectModelStatusRequestDTO,
  getProjectModelStatusResponseDTO,
  convert3DTileRequestDTO,
  convert3DTileResponseDTO,
  convertTerrainRequestDTO,
  convertTerrainResponseDTO,
  convertProjectModelRequestDTO,
  convertProjectModelResponseDTO,
} from "./converter3D.dto.js";
import { getConverter3DService } from "./converter3D.service.js";
import { authMiddleware } from "../auth/auth.middleware.js";
import { Type } from "@sinclair/typebox";
import { getBlobStorageService } from "../blobStorage/blobStorage.service.js";

const converter3DController = createController()
  .use(authMiddleware)
  .rootPath("/converter3D");

converter3DController
  .addRoute("POST", "/convertProjectModel")
  .body(convertProjectModelRequestDTO)
  .output(convertProjectModelResponseDTO)
  .handler(async ({ services, body }) => {
    const converter3DService = await getConverter3DService(services);

    return await converter3DService.convertProjectModel(
      body.blobRef,
      body.fileName,
      body.srcSRS
    );
  });

converter3DController
  .addRoute("POST", "/getProjectModelStatus")
  .body(getProjectModelStatusRequestDTO)
  .output(getProjectModelStatusResponseDTO)
  .handler(async ({ body, services }) => {
    const converter3DService = await getConverter3DService(services);

    return await converter3DService.getProjectModelStatus(
      body.jobId,
      body.secret
    );
  });

converter3DController
  .addRoute("POST", "/downloadProjectModel")
  .body(downloadProjectModelRequestDTIO)
  .output(Type.Object({ href: Type.String() }))
  .handler(async ({ body, services }) => {
    const converter3DService = await getConverter3DService(services);

    const { href } = await converter3DService.downloadProjectModel(
      body.jobId,
      body.projectId,
      body.secret
    );

    return { href };
  });

converter3DController
  .addRoute("POST", "/convertTerrain")
  .body(convertTerrainRequestDTO)
  .output(convertTerrainResponseDTO)
  .handler(async ({ services, body }) => {
    const converter3DService = await getConverter3DService(services);

    return await converter3DService.convertTerrain(
      body.blobRef,
      body.name,
      body.srcSRS
    );
  });

converter3DController
  .addRoute("POST", "/convert3DTile")
  .body(convert3DTileRequestDTO)
  .output(convert3DTileResponseDTO)
  .handler(async ({ services, body }) => {
    const converter3DService = await getConverter3DService(services);

    return await converter3DService.convert3DTile(
      body.blobRef,
      body.name,
      body.srcSRS
    );
  });

converter3DController
  .addRoute("GET", "/getUploadSASToken")
  .output(Type.String())
  .handler(async ({ services }) => {
    const blobStorageService = await getBlobStorageService(services);

    return await blobStorageService.getUploadSASUrl("upload-general");
  });

/*
AUTOGENERATED!
*/

export { converter3DController };
