import {
  createWorker,
} from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";
import { getDbService } from "../../@internals/index.js";
import dayjs from "dayjs";
import { BullMQOtel } from "bullmq-otel";

const removeOldEventsWorker = createWorker()
  .queue("{removeOldEvents-queue}")
  .job<Job<void, void>>()
  .upsertJobScheduler("removeOldEventsScheduler", {
    pattern: "0 0 * * *", // every day at 00:00
  })
  .options({ telemetry: new BullMQOtel("bullmq") })
  .connection(defaultConnection)
  .processor(async (_, { services }) => {
    const dbService = await getDbService(services);

    await dbService.event.findMany({
      where: {
        endTime: {
          lt: dayjs().subtract(1, "day").toISOString(), // delete all events that are older than 1 day
        },
      },
    });
  });

/*
AUTOGENERATED!
*/

export default removeOldEventsWorker;
