import { createController } from "@csi-foxbyte/fastify-toab";
import { Type } from "@sinclair/typebox";

const statsController = createController().rootPath("/stats");

statsController
  .addRoute("GET", "/gc")
  .output(Type.Boolean())
  .handler(async () => {
    global.gc?.();

    return !!global.gc;
  });

statsController
  .addRoute("GET", "/")
  .output(
    Type.Object({
      memoryUsage: Type.Object({
        rss: Type.Number(),
        heapTotal: Type.Number(),
        heapUsed: Type.Number(),
        external: Type.Number(),
        arrayBuffers: Type.Number(),
      }),
    })
  )
  .handler(async () => {
    return { memoryUsage: process.memoryUsage() };
  });

/*
AUTOGENERATED!
*/

export { statsController };
