import {
  createService,
  InferService,
  ServiceContainer,
} from "@csi-foxbyte/fastify-toab";

const statsService = createService("stats", async () => {
  return {};
});

/*
AUTOGENERATED!
*/

export { statsService };
export type StatsService = InferService<typeof statsService>;
export function getStatsService(deps: ServiceContainer) {
  return deps.get<StatsService>(statsService.name);
}
