import { createController } from "@csi-foxbyte/fastify-toab";
import { Type } from "@sinclair/typebox";
import { getDbService } from "../db/db.service.js";
import { on } from "events";

const statsController = createController().rootPath("/stats");

statsController
  .addRoute("GET", "/gc")
  .output(Type.Boolean())
  .handler(async () => {
    global.gc?.();

    return !!global.gc;
  });

statsController
  .addRoute("GET", "/")
  .output(
    Type.Object({
      memoryUsage: Type.Object({
        rss: Type.Number(),
        heapTotal: Type.Number(),
        heapUsed: Type.Number(),
        external: Type.Number(),
        arrayBuffers: Type.Number(),
      }),
    })
  )
  .handler(async () => {
    return { memoryUsage: process.memoryUsage() };
  });

statsController
  .addRoute("SSE", "/test")
  .output(Type.String())
  .handler(async function* ({ signal, services }) {
    const dbService = await getDbService(services);

    yield "OK";

    for await (const [data] of on(
      dbService.rawClient.role.subscribe({ operations: ["*"] }),
      "change",
      { signal }
    )) {
      yield data;
    }
  });

/*
AUTOGENERATED!
*/

export { statsController };
