import { createWorker } from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";

const deleteInactiveUsersWorker = createWorker()
    .queue("{user-deleteInactiveUsers-queue}")
    .job<Job<void, void>>()
    .upsertJobScheduler("user-deleteInactiveUsers-jobScheduler", {
        pattern: "0 0 * * *",
    })
    .connection(defaultConnection)
    .processor(async () => {
        return;
    });

/*
AUTOGENERATED!
*/

export default deleteInactiveUsersWorker;
