/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";
import appDownload_appDownload$service from "./appDownload/appDownload.service.js";
import auth_auth$service from "./auth/auth.service.js";
import baseLayer_baseLayer$service from "./baseLayer/baseLayer.service.js";
import blobStorage_blobStorage$service from "./blobStorage/blobStorage.service.js";
import cache_cache$service from "./cache/cache.service.js";
import configuration_configuration$service from "./configuration/configuration.service.js";
import converter3D_converter3D$service from "./converter3D/converter3D.service.js";
import db_db$service from "./db/db.service.js";
import email_email$service from "./email/email.service.js";
import events_events$service from "./events/events.service.js";
import notification_notification$service from "./notification/notification.service.js";
import prisma_prisma$service from "./prisma/prisma.service.js";
import project_project$service from "./project/project.service.js";
import stats_stats$service from "./stats/stats.service.js";
import token_token$service from "./token/token.service.js";
import translation_translation$service from "./translation/translation.service.js";
import user_user$service from "./user/user.service.js";
import blobStorage_workers_deleteBlob$worker from "./blobStorage/workers/deleteBlob.worker.js";
import converter3D_workers_convert3DTiles$worker from "./converter3D/workers/convert3DTiles.worker.js";
import converter3D_workers_convertProjectModel$worker from "./converter3D/workers/convertProjectModel.worker.js";
import converter3D_workers_convertTerrain$worker from "./converter3D/workers/convertTerrain.worker.js";
import converter3D_workers_convertWMSWMTS$worker from "./converter3D/workers/convertWMSWMTS.worker.js";
import converter3D_workers_updateConverterWorkerConfigurations$worker from "./converter3D/workers/updateConverterWorkerConfigurations.worker.js";
import events_workers_removeOldEvents$worker from "./events/workers/removeOldEvents.worker.js";
import user_workers_deleteInactiveUsers$worker from "./user/workers/deleteInactiveUsers.worker.js";
import appDownload_appDownload$controller from "./appDownload/appDownload.controller.js";
import baseLayer_baseLayer$controller from "./baseLayer/baseLayer.controller.js";
import converter3D_converter3D$controller from "./converter3D/converter3D.controller.js";
import events_events$controller from "./events/events.controller.js";
import project_project$controller from "./project/project.controller.js";
import public_public$controller from "./public/public.controller.js";
import stats_stats$controller from "./stats/stats.controller.js";
import user_user$controller from "./user/user.controller.js";

export async function getRegistries(dontInitializeWorkers?: boolean) {
  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  const serviceRegistry = new ServiceRegistry(workerRegistryRef);
  serviceRegistry.register(appDownload_appDownload$service);
  serviceRegistry.register(auth_auth$service);
  serviceRegistry.register(baseLayer_baseLayer$service);
  serviceRegistry.register(blobStorage_blobStorage$service);
  serviceRegistry.register(cache_cache$service);
  serviceRegistry.register(configuration_configuration$service);
  serviceRegistry.register(converter3D_converter3D$service);
  serviceRegistry.register(db_db$service);
  serviceRegistry.register(email_email$service);
  serviceRegistry.register(events_events$service);
  serviceRegistry.register(notification_notification$service);
  serviceRegistry.register(prisma_prisma$service);
  serviceRegistry.register(project_project$service);
  serviceRegistry.register(stats_stats$service);
  serviceRegistry.register(token_token$service);
  serviceRegistry.register(translation_translation$service);
  serviceRegistry.register(user_user$service);

  const workerRegistry = new WorkerRegistry(serviceRegistry);
  await workerRegistry.register(blobStorage_workers_deleteBlob$worker, dontInitializeWorkers);
  await workerRegistry.register(converter3D_workers_convert3DTiles$worker, dontInitializeWorkers);
  await workerRegistry.register(converter3D_workers_convertProjectModel$worker, dontInitializeWorkers);
  await workerRegistry.register(converter3D_workers_convertTerrain$worker, dontInitializeWorkers);
  await workerRegistry.register(converter3D_workers_convertWMSWMTS$worker, dontInitializeWorkers);
  await workerRegistry.register(converter3D_workers_updateConverterWorkerConfigurations$worker, dontInitializeWorkers);
  await workerRegistry.register(events_workers_removeOldEvents$worker, dontInitializeWorkers);
  await workerRegistry.register(user_workers_deleteInactiveUsers$worker, dontInitializeWorkers);
  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  const controllerRegistry = new ControllerRegistry(serviceRegistry);
  controllerRegistry.register(appDownload_appDownload$controller);
  controllerRegistry.register(baseLayer_baseLayer$controller);
  controllerRegistry.register(converter3D_converter3D$controller);
  controllerRegistry.register(events_events$controller);
  controllerRegistry.register(project_project$controller);
  controllerRegistry.register(public_public$controller);
  controllerRegistry.register(stats_stats$controller);
  controllerRegistry.register(user_user$controller);

  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
