/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";

import { authService } from "./auth/auth.service.js";
import { blobStorageService } from "./blobStorage/blobStorage.service.js";
import { cacheService } from "./cache/cache.service.js";
import { configurationService } from "./configuration/configuration.service.js";
import { converter3DService } from "./converter3D/converter3D.service.js";
import { dbService } from "./db/db.service.js";
import { eventsService } from "./events/events.service.js";
import { deleteBlobWorker } from "./blobStorage/workers/deleteBlob.worker.js";
import { convert3DTilesWorker } from "./converter3D/workers/convert3DTiles.worker.js";
import { convertProjectModelWorker } from "./converter3D/workers/convertProjectModel.worker.js";
import { convertTerrainWorker } from "./converter3D/workers/convertTerrain.worker.js";
import { converter3DController } from "./converter3D/converter3D.controller.js";
import { eventsController } from "./events/events.controller.js";

export async function getRegistries(dontInitializeWorkers?: boolean) {
  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  const serviceRegistry = new ServiceRegistry(workerRegistryRef);
  serviceRegistry.register(authService);
  serviceRegistry.register(blobStorageService);
  serviceRegistry.register(cacheService);
  serviceRegistry.register(configurationService);
  serviceRegistry.register(converter3DService);
  serviceRegistry.register(dbService);
  serviceRegistry.register(eventsService);

  const workerRegistry = new WorkerRegistry(serviceRegistry);
  await workerRegistry.register(deleteBlobWorker, dontInitializeWorkers);
  await workerRegistry.register(convert3DTilesWorker, dontInitializeWorkers);
  await workerRegistry.register(convertProjectModelWorker, dontInitializeWorkers);
  await workerRegistry.register(convertTerrainWorker, dontInitializeWorkers);
  workerRegistryRef.current = workerRegistry;

  const controllerRegistry = new ControllerRegistry(serviceRegistry);
  controllerRegistry.register(converter3DController);
  controllerRegistry.register(eventsController);

  return { controllerRegistry, serviceRegistry, workerRegistry };
}