/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";import p_090dea03a1fd4f4e93015d81869fbcd7 from "./appDownload/appDownload.service.js";
import p_72ba68c465b142e5bfec8331d1d38e0b from "./auth/auth.service.js";
import p_1f9c4cf63e1f49f48c96158267eb3e7a from "./baseLayer/baseLayer.service.js";
import p_5eb1ae3b8c754da7bf6eb1b3c852560f from "./blobStorage/blobStorage.service.js";
import p_0c3ce98d4a724295896b341ceaef1584 from "./cache/cache.service.js";
import p_951e649e7ebc43e9b302326509f0ab50 from "./configuration/configuration.service.js";
import p_c4255df6cbca4ebd81466fe53a36e5da from "./converter3D/converter3D.service.js";
import p_0eff0003cfa947d8b42e6c9d8f5b3266 from "./db/db.service.js";
import p_5fe10d2ad6354369b058b43548c65ad2 from "./email/email.service.js";
import p_fc85443afb0e4be5bc03cde119eea07c from "./events/events.service.js";
import p_73689c8130b140c6aef20028223f5b55 from "./notification/notification.service.js";
import p_5752d66f8c7748b68e61d43137df9224 from "./prisma/prisma.service.js";
import p_654b7d65dbe6400db9695cf2c59e6d10 from "./project/project.service.js";
import p_54dd851164ee4f22b00c5aa76696b6e0 from "./stats/stats.service.js";
import p_6c3272edcd8d4d3b8c50ead50148c4fb from "./token/token.service.js";
import p_e6aa4ce8af8f44b69ee6ed1752ab9e61 from "./translation/translation.service.js";
import p_91a5ac723142413c9d4f3d68732ff67a from "./user/user.service.js";
import p_8764954812b54074b0c118ef1c91a394 from "./blobStorage/workers/deleteBlob.worker.js";
import p_3f93afb1585740abb50a90642cf1d62b from "./converter3D/workers/convert3DTiles.worker.js";
import p_666043d8008d40149c26164a0e79e7b6 from "./converter3D/workers/convertProjectModel.worker.js";
import p_c0762619ece64e07bfbb5367853fddf1 from "./converter3D/workers/convertTerrain.worker.js";
import p_0b4ec92716c34e1f946fd0db2438bc2d from "./converter3D/workers/updateConverterWorkerConfigurations.worker.js";
import p_46d4a1c19f034fdab5cd7a6743d7a529 from "./events/workers/removeOldEvents.worker.js";
import p_26b6af4ee6344983996b60a16de49f52 from "./user/workers/deleteInactiveUsers.worker.js";
import p_dc1443695a3c4ab787eb68f00a35b2dc from "./appDownload/appDownload.controller.js";
import p_6ee5ccc197244095a9cfe2048d45058a from "./baseLayer/baseLayer.controller.js";
import p_417314b539874b418769c5e4e6d7c8df from "./converter3D/converter3D.controller.js";
import p_fde97b7ded5e45d7b83e991f73982aeb from "./events/events.controller.js";
import p_184b9b166e134317850cab9f0bd52e60 from "./project/project.controller.js";
import p_d592d9a428774a44b9c36ef29c8d7b5b from "./public/public.controller.js";
import p_ede3896516a2476c8b8e3d42f4ea217a from "./stats/stats.controller.js";
import p_9ebcca731c19433f879594004be40e5a from "./user/user.controller.js";

export async function getRegistries(dontInitializeWorkers?: boolean) {
  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  const serviceRegistry = new ServiceRegistry(workerRegistryRef);
  serviceRegistry.register(p_090dea03a1fd4f4e93015d81869fbcd7);
  serviceRegistry.register(p_72ba68c465b142e5bfec8331d1d38e0b);
  serviceRegistry.register(p_1f9c4cf63e1f49f48c96158267eb3e7a);
  serviceRegistry.register(p_5eb1ae3b8c754da7bf6eb1b3c852560f);
  serviceRegistry.register(p_0c3ce98d4a724295896b341ceaef1584);
  serviceRegistry.register(p_951e649e7ebc43e9b302326509f0ab50);
  serviceRegistry.register(p_c4255df6cbca4ebd81466fe53a36e5da);
  serviceRegistry.register(p_0eff0003cfa947d8b42e6c9d8f5b3266);
  serviceRegistry.register(p_5fe10d2ad6354369b058b43548c65ad2);
  serviceRegistry.register(p_fc85443afb0e4be5bc03cde119eea07c);
  serviceRegistry.register(p_73689c8130b140c6aef20028223f5b55);
  serviceRegistry.register(p_5752d66f8c7748b68e61d43137df9224);
  serviceRegistry.register(p_654b7d65dbe6400db9695cf2c59e6d10);
  serviceRegistry.register(p_54dd851164ee4f22b00c5aa76696b6e0);
  serviceRegistry.register(p_6c3272edcd8d4d3b8c50ead50148c4fb);
  serviceRegistry.register(p_e6aa4ce8af8f44b69ee6ed1752ab9e61);
  serviceRegistry.register(p_91a5ac723142413c9d4f3d68732ff67a);

  const workerRegistry = new WorkerRegistry(serviceRegistry);
  await workerRegistry.register(p_8764954812b54074b0c118ef1c91a394, dontInitializeWorkers);
  await workerRegistry.register(p_3f93afb1585740abb50a90642cf1d62b, dontInitializeWorkers);
  await workerRegistry.register(p_666043d8008d40149c26164a0e79e7b6, dontInitializeWorkers);
  await workerRegistry.register(p_c0762619ece64e07bfbb5367853fddf1, dontInitializeWorkers);
  await workerRegistry.register(p_0b4ec92716c34e1f946fd0db2438bc2d, dontInitializeWorkers);
  await workerRegistry.register(p_46d4a1c19f034fdab5cd7a6743d7a529, dontInitializeWorkers);
  await workerRegistry.register(p_26b6af4ee6344983996b60a16de49f52, dontInitializeWorkers);
  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  const controllerRegistry = new ControllerRegistry(serviceRegistry);
  controllerRegistry.register(p_dc1443695a3c4ab787eb68f00a35b2dc);
  controllerRegistry.register(p_6ee5ccc197244095a9cfe2048d45058a);
  controllerRegistry.register(p_417314b539874b418769c5e4e6d7c8df);
  controllerRegistry.register(p_fde97b7ded5e45d7b83e991f73982aeb);
  controllerRegistry.register(p_184b9b166e134317850cab9f0bd52e60);
  controllerRegistry.register(p_d592d9a428774a44b9c36ef29c8d7b5b);
  controllerRegistry.register(p_ede3896516a2476c8b8e3d42f4ea217a);
  controllerRegistry.register(p_9ebcca731c19433f879594004be40e5a);

  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
